### ISSUE TITLE
ActionView::MissingTemplate

### ISSUE THREAD

**Issue by alexvirtualbr** [rails/actiontext#15]
Hey guys,

I did a test on rails 5.2.0 and I had a partial result using:
## gem 'trix

And the ActionText complain:
Missing partial action_text/attachables/_remote_image with {:locale=>[:en], :formats=>[:html, :text, :js, :css, :ics, :csv, :vcf, :vtt, :png, :jpeg, :gif, :bmp, :tiff, :svg, :mpeg, :mp3, :ogg, :m4a, :webm, :mp4, :otf, :ttf, :woff, :woff2, :xml, :rss, :atom, :yaml, :multipart_form, :url_encoded_form, :json, :pdf, :zip, :gzip], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :jbuilder]}. Searched in:

**Comment by javan** [comment]
Thanks!
