### ISSUE TITLE
Provide a meaningful error when forgetting has_rich_text in model

### ISSUE THREAD

**Issue by albertoalmagro** [rails/actiontext#19]
Hello everyone!

First of all, thanks for creating this gem and deciding to include it in Rails 6 🎉 🙏 

Yesterday while I was watching @dhh 's demo video I decided to follow the steps to try ActionText myself. By doing this I luckily forgot to add the following `has_rich_text` class method to Post:
```ruby
class Post < ApplicationRecord
  has_rich_text :content
end
```
The consequence was that when I tried to render the form with the rich text editor I got the following error:
```bash
ActionView::Template::Error (undefined method `body' for nil:NilClass):
    17:   </div>
    18: 
    19:   <div class="field">
    20:     <%= form.rich_text_area :content %>
    21:   </div>
    22: 
    23:   <div class="actions">
```
I would like to submit a patch that would make ActionText able to suggest the user that the `has_rich_text` class method for `:content` in the `Post` model may need to be added. Would you be happy with that?

Thanks in advance!

**Comment by dhh** [comment]
👍

**Comment by javan** [comment]
Wonder if we should go the other direction and and render an empty rich text editor instead of raising an error. That's what Rails does currently with other form fields. For example, the following doesn't raise anything:
```erb
<%= form_with(model: post) do |form| %>
  <div class="field">
    <%= form.text_area :not_an_attribute %>
  </div>
<% end %>
```
👇
```html
<form action="/posts" accept-charset="UTF-8" method="post">
  <div class="field">
    <textarea name="post[not_an_attribute]" id="post_not_an_attribute"></textarea>
  </div>
</form>
```

**Comment by dhh** [comment]
I like that better, actually, too 👍

**Comment by albertoalmagro** [comment]
While I think that approach gives less information to the user, I see the value in behaving as Rails does for the future integration. Let me then please close my current PR and prepare a new one 👍
