### ISSUE TITLE
i18n considerations

### ISSUE THREAD

**Issue by djshitcoin** [rails/actiontext#32]
Hello,

I like the inclusion of a rich-text editor in rails by default.

One issue I'd like to raise is internationalization/translations. I've been using the `globalize` gem to save translation records for fields on models that have translations. Now I was wondering if this will work for rich text fields, too.

**Comment by IvanGrgurevic** [comment]
I gave it a try and doesn't quite work as expected but I've come up with a quick hack to get it working. I delegated all the methods `has_rich_text` creates to the translation and attached `has_rich_text :content` to the translation class by opening up `globalize`'s nested `Translation` class. You can find an example below with a `Post` model that has `content` as the rich text field.

Disclaimer: Not fully tested.

```
class Post < ApplicationRecord
  translates :title, :content, touch: true

  delegate :content, to: :translation
  delegate :content=, to: :translation
  delegate :rich_text_content, to: :translation
  delegate :with_rich_text_content, to: :translation
  delegate :with_rich_text_content_and_embeds, to: :translation

  class Translation
    has_rich_text :body
  end
end
```

**Comment by georgeclaghorn** [comment]
Action Text has been merged into Rails. Please do investigate whether Action Text plays nicely with popular plugins and report back to [rails/rails](https://github.com/rails/rails) if there’s anything we can reasonably do in the framework to address incompatibilities.
