### ISSUE TITLE
undefined method `url_expires_in` for nil:NilClass:

### ISSUE THREAD

**Issue by elliottyson** [rails/actiontext#33]
Hello,

I am having troubles when I want to add pictures.
There is no issue when I copy paste a picture directly in the text editor. However when I try to drag and drop a picture from a folder, it raises an error in **ActiveStorage::DirectUploadsController** line 19 with the error `NoMethodError - undefined method 'url_expires_in' for nil:NilClass:`
Any idea of where it can come from?

Thanks

**Comment by simonini** [comment]
Here same issue, i'm using rails 5.2.

**Comment by simonini** [comment]
In my case, I've solved with a full and correct configuration of active storage.

**Comment by elliottyson** [comment]
Hey @simonini thanks for the feedback, rails 5.2. as well. What do you mean by a full and correct config of active storage ?

**Comment by simonini** [comment]
In my case I had to reconfigure activestorage with 

`rails active_storage:install`

and after I add the storage.yml

**Comment by a-ta-ta** [comment]
Assuming you're in development, just try adding in your `config/environments/development.rb` the following line:
`config.active_storage.service = :local`
