### ISSUE TITLE
UniqueViolation: Error in Gallery edits (Rails 5.2.1)

### ISSUE THREAD

**Issue by wxmn** [rails/actiontext#36]
I *know* action_text doesn't support Rails 5.2.1 (and depends on Rails 6.0.x). 

That said, with minimal work, it's working 99% in Rails 5.2.1 and now the only issue I'm running into is in a very specific scenario (below), and I was wondering if anyone here knows whether it's related to reliance on a specific update in Rails 6 (related to ActiveStorage or ActiveRecord) that I could patch in to make it work in Rails 5.2.1:

**Environment**

- New Rails 5.2.1 app
- Add latest actiontext and webpacker versions from Github to Gemfile and bundle install
- Install webpacker
- Make sure javascript_pack_tag 'application' is in application layout
- Install actiontext
- Run migrations
- Add Post scaffold with title:string and run migrations
- Add rich_text_field :content to Post.rb, then update _form.erb, show.erb, and posts_controller post_params
- The only Rails 5.2.1 specific change (relevant to this) is to simply remove the image transforms from _blob.html.erb: `<%= image_tag blob.representation({})`

**Issue**

- Go to posts#new and add a title and some content
- Upload 2 images to the rich_text_field (by drag-and-dropping)
- Save (which works fine and displays correctly on posts#show)
- Then try to edit the post, and specifically edit rich_text_field so that 1 or 2 of original 2 images are still present (but something about the content is different than before)
- Save 
- PG::UniqueViolation Error

`PG::UniqueViolation: ERROR: duplicate key value violates unique constraint "index_active_storage_attachments_uniqueness" DETAIL: Key (record_type, record_id, name, blob_id)=(ActionText::RichText, 349d05dd-cc7c-4e51-973d-24ff9e382e10, embeds, 1e794d34-6a14-4a80-9aeb-d31e6e1a1494) already exists. : INSERT INTO "active_storage_attachments" ("name", "record_id", "record_type", "blob_id", "created_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"`

This does NOT happen in Rails 6.0.0.alpha. This DOES happen in Rails 5.2.1 without uuid's and without postgres.

It looks like it's trying to re-upload the image, even though it's already been uploaded.

I realize this is not a bug, so I'm sorry to clog up issues, but if anyone knows off the top of their head why this might be happening in Rails 5.2.1 (and not with Rails 6.0.0.alpha), I would deeply appreciate some help!

Thanks!!

**Comment by javan** [comment]
> The only Rails 5.2.1 specific change (relevant to this) is to simply remove the image transforms from _blob.html.erb: `<%= image_tag blob.representation({}) %>`

Does `<%= image_tag blob %>` work?

**Comment by wxmn** [comment]
Yes it does @javan

**Comment by javan** [comment]
Cool, you can probably use the older representation API for Rails 5.2.1 support. See https://github.com/rails/actiontext/commit/dec130a80c4947f749782347d03469bd7358c43b.

**Comment by wxmn** [comment]
Thanks @javan! Our main issue isn't old representation API, though, it's the violates unique constraint issue. Any thoughts on that? Thanks!

**Comment by javan** [comment]
That seems like a general ActiveStorage issue… @georgeclaghorn?

**Comment by wxmn** [comment]
The following method ended up being the issue:

`module ActiveStorage
  class Attached::Many < Attached

    def attach(*attachables)
      attachables.flatten.collect do |attachable|
        if record.new_record?
          attachments.build(record: record, blob: create_blob_from(attachable))
        else
          attachments.create!(record: record, blob: create_blob_from(attachable))
        end
      end
    end

  end
end`

It seems to work if you just add an `attachments.exists?` query before `attachments.create!` to prevent a violates unique index error when it tries to create the same attachment twice.

It looks like this entire part of ActiveStorage was totally rewritten for Rails 6, so now I understand why there's no Rails 5.2 support :-) 

Excited for ActionText's official launch in Rails 6! It's truly an awesome tool.

**Comment by damienjbyrne** [comment]
Thanks @wxmn, I was looking at the exact same situation, issue, and solution. Nice to have a second confirmation.
