### ISSUE TITLE
UseCase video embedding

### ISSUE THREAD

**Issue by tordans** [rails/actiontext#37]
Hi, I love the idea of actiontext.
I looked into our own RTE implementation and found a use case that is not supported yet:

Embedding of external videos.

UseCase: I want to write a blog post and add a youtube or vimeo video.
Ideally, I would want to see a preview of the video in my editor - same as with images.

The way we do it right now: Authors can paste a video URL in the editor. Once we save the content we use oembed to change the URL to the preview-snipped. We then save both, the original text and the output-text which includes the youtube (…) video-snipped. We then display the output-text.

This process would still work with actiontext/trix, but it's not on the same level as working with images.

Are there other ways to handle this within actiontext?
Native support for embedding of external videos?
Or an api that allows to handle the trix-ui-part (paste, display a preview) and rendering part?

Thanks

**Comment by georgeclaghorn** [comment]
Action Text’s attachment support can be used to implement video embeds. In broad strokes, here’s how we do it in Basecamp:

1. When an embed is requested, we issue a request to the server to create an `Embed` record whose attributes are populated using OEmbed.
2. The `Embed` model mixes in `ActionText::Attachable`. The JSON response from the server contains the embed’s `ActionText::Attachable#attachable_sgid`.
3. On the client-side, we use Trix’s [content attachment API](https://github.com/basecamp/trix#inserting-a-content-attachment) to insert markup representing the embed into the document.
4. When displaying rich-text content containing embeds, Action Text automatically renders the `embeds/_embed.html.erb` partial (just like it automatically renders `active_storage/blobs/_blob.html.erb` for file attachments).

Hope that helps!
