### ISSUE TITLE
Add "insert image" button to default setup

### ISSUE THREAD

**Issue by tordans** [rails/actiontext#39]
Our user base is not used to drag and drop as an action to add images to RTE-areas.

Therefore, we have a toolbar button to "add image".

I suggest adding such a button to the default setup in action text so there is a clear affordance that shows me how to add a picture.

**Comment by simonini** [comment]
I have same suggestion.

**Comment by nikolaokonesh** [comment]
I have same suggestion.

**Comment by georgeclaghorn** [comment]
Default toolbar buttons are [Trix](https://github.com/basecamp/trix)’s domain, not Action Text’s. Please do investigate!
