### ISSUE TITLE
couldn't find file 'trix/dist/trix' with type 'text/css'

### ISSUE THREAD

**Issue by gobijan** [rails/actiontext#40]
I just installed wanted to test drive Rails version: 6.0.0.alpha
(Ruby version: 2.5.3 (x86_64-darwin18)) and followed this guide to try out action text:
https://dev.to/adrienpoly/step-by-step-guide-to-test-rails-activetext-4b8o

Trix including image upload works but I have to throw out this line: https://github.com/rails/actiontext/blob/18974137be2c4027dfcf430668edd712e7ec011b/lib/templates/actiontext.scss#L6

Otherwise I get the following error:

> couldn't find file 'trix/dist/trix' with type 'text/css'
Checked in these paths: 
  /Users/bijan/Desktop/yabe/yabe6/app/assets/config
  /Users/bijan/Desktop/yabe/yabe6/app/assets/images
  /Users/bijan/Desktop/yabe/yabe6/app/assets/stylesheets
  /Users/bijan/.asdf/installs/ruby/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/rails-1cc46865ecfe/actioncable/app/assets/javascripts
  /Users/bijan/.asdf/installs/ruby/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/rails-1cc46865ecfe/activestorage/app/assets/javascripts
  /Users/bijan/.asdf/installs/ruby/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/rails-1cc46865ecfe/actionview/app/assets/javascripts
  /Users/bijan/.asdf/installs/ruby/2.5.3/lib/ruby/gems/2.5.0/gems/turbolinks-source-5.2.0/lib/assets/javascripts

So Trix is unfortunately completely unstyled. Am I missing something?

**Comment by adrienpoly** [comment]
Hello

That is strange I haven't retested it for a while 
here is a repo you can clone that for sure was working a few weeks ago: https://github.com/adrienpoly/yabe

If it is also broken let me know I will investigate the potential breaking changes of the latest commits

**Comment by gobijan** [comment]
I downloaded your repo and it works. But generating a new project using current master fails for me:

> ~/Desktop/rails6playground 
> ❯ bundle exec rails new yaberetry --edge
>       create  
>       create  README.md
>       create  Rakefile
>       create  .ruby-version
>       create  config.ru
>       create  .gitignore
>       create  Gemfile
>          run  git init from "."
> Initialized empty Git repository in /Users/bijan/Desktop/rails6playground/yaberetry/.git/
>       create  package.json
>       create  app
>       create  app/assets/config/manifest.js
>       create  app/assets/stylesheets/application.css
>       create  app/channels/application_cable/channel.rb
>       create  app/channels/application_cable/connection.rb
>       create  app/controllers/application_controller.rb
>       create  app/helpers/application_helper.rb
>       create  app/javascript/channels/consumer.js
>       create  app/javascript/channels/index.js
>       create  app/javascript/packs/application.js
>       create  app/jobs/application_job.rb
>       create  app/mailers/application_mailer.rb
>       create  app/models/application_record.rb
>       create  app/views/layouts/application.html.erb
>       create  app/views/layouts/mailer.html.erb
>       create  app/views/layouts/mailer.text.erb
>       create  app/assets/images/.keep
>       create  app/controllers/concerns/.keep
>       create  app/models/concerns/.keep
>       create  bin
>       create  bin/rails
>       create  bin/rake
>       create  bin/setup
>       create  bin/update
>       create  bin/yarn
>       create  config
>       create  config/routes.rb
>       create  config/application.rb
>       create  config/environment.rb
>       create  config/cable.yml
>       create  config/puma.rb
>       create  config/spring.rb
>       create  config/storage.yml
>       create  config/environments
>       create  config/environments/development.rb
>       create  config/environments/production.rb
>       create  config/environments/test.rb
>       create  config/initializers
>       create  config/initializers/application_controller_renderer.rb
>       create  config/initializers/assets.rb
>       create  config/initializers/backtrace_silencers.rb
>       create  config/initializers/content_security_policy.rb
>       create  config/initializers/cookies_serializer.rb
>       create  config/initializers/cors.rb
>       create  config/initializers/filter_parameter_logging.rb
>       create  config/initializers/inflections.rb
>       create  config/initializers/mime_types.rb
>       create  config/initializers/new_framework_defaults_6_0.rb
>       create  config/initializers/wrap_parameters.rb
>       create  config/locales
>       create  config/locales/en.yml
>       create  config/master.key
>       append  .gitignore
>       create  config/boot.rb
>       create  config/database.yml
>       create  db
>       create  db/seeds.rb
>       create  lib
>       create  lib/tasks
>       create  lib/tasks/.keep
>       create  lib/assets
>       create  lib/assets/.keep
>       create  log
>       create  log/.keep
>       create  public
>       create  public/404.html
>       create  public/422.html
>       create  public/500.html
>       create  public/apple-touch-icon-precomposed.png
>       create  public/apple-touch-icon.png
>       create  public/favicon.ico
>       create  public/robots.txt
>       create  tmp
>       create  tmp/.keep
>       create  tmp/cache
>       create  tmp/cache/assets
>       create  vendor
>       create  vendor/.keep
>       create  test/fixtures
>       create  test/fixtures/.keep
>       create  test/fixtures/files
>       create  test/fixtures/files/.keep
>       create  test/controllers
>       create  test/controllers/.keep
>       create  test/mailers
>       create  test/mailers/.keep
>       create  test/models
>       create  test/models/.keep
>       create  test/helpers
>       create  test/helpers/.keep
>       create  test/integration
>       create  test/integration/.keep
>       create  test/test_helper.rb
>       create  test/system
>       create  test/system/.keep
>       create  test/application_system_test_case.rb
>       create  storage
>       create  storage/.keep
>       create  tmp/storage
>       create  tmp/storage/.keep
>       remove  config/initializers/cors.rb
>       remove  config/initializers/new_framework_defaults_6_0.rb
>          run  bundle install
> Fetching https://github.com/rails/rails.git
> Fetching https://github.com/rails/webpacker.git
> Fetching https://github.com/rails/web-console.git
> The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
> Fetching gem metadata from https://rubygems.org/.........
> Fetching gem metadata from https://rubygems.org/..........
> Fetching gem metadata from https://rubygems.org/..........
> Resolving dependencies...
> Using rake 12.3.1
> Using concurrent-ruby 1.1.3
> Using i18n 1.1.1
> Using minitest 5.11.3
> Using thread_safe 0.3.6
> Using tzinfo 1.2.5
> Using activesupport 6.0.0.alpha from https://github.com/rails/rails.git (at master@1cc4686)
> Using builder 3.2.3
> Using erubi 1.7.1
> Using mini_portile2 2.3.0
> Using nokogiri 1.8.5
> Using rails-dom-testing 2.0.3
> Using crass 1.0.4
> Using loofah 2.2.3
> Using rails-html-sanitizer 1.0.4
> Using actionview 6.0.0.alpha from https://github.com/rails/rails.git (at master@1cc4686)
> Using rack 2.0.6
> Using rack-test 1.1.0
> Using actionpack 6.0.0.alpha from https://github.com/rails/rails.git (at master@1cc4686)
> Using nio4r 2.3.1
> Using websocket-extensions 0.1.3
> Using websocket-driver 0.7.0
> Using actioncable 6.0.0.alpha from https://github.com/rails/rails.git (at master@1cc4686)
> Using globalid 0.4.1
> Using activejob 6.0.0.alpha from https://github.com/rails/rails.git (at master@1cc4686)
> Using mini_mime 1.0.1
> Using mail 2.7.1
> Using actionmailer 6.0.0.alpha from https://github.com/rails/rails.git (at master@1cc4686)
> Using activemodel 6.0.0.alpha from https://github.com/rails/rails.git (at master@1cc4686)
> Using activerecord 6.0.0.alpha from https://github.com/rails/rails.git (at master@1cc4686)
> Using mimemagic 0.3.2
> Using marcel 0.3.3
> Using activestorage 6.0.0.alpha from https://github.com/rails/rails.git (at master@1cc4686)
> Using public_suffix 3.0.3
> Using addressable 2.5.2
> Using io-like 0.3.0
> Using archive-zip 0.11.0
> Using bindex 0.5.0
> Using msgpack 1.2.4
> Using bootsnap 1.3.2
> Using bundler 1.17.1
> Using byebug 10.0.2
> Using regexp_parser 1.2.0
> Using xpath 3.2.0
> Using capybara 3.10.1
> Using ffi 1.9.25
> Using childprocess 0.9.0
> Using chromedriver-helper 2.1.0
> Using multi_json 1.13.1
> Using jbuilder 2.8.0
> Using rb-fsevent 0.10.3
> Using rb-inotify 0.9.10
> Using ruby_dep 1.5.0
> Using listen 3.1.5
> Using method_source 0.9.2
> Using puma 3.12.0
> Using rack-proxy 0.6.5
> Using thor 0.20.3
> Using railties 6.0.0.alpha from https://github.com/rails/rails.git (at master@1cc4686)
> Using sprockets 3.7.2
> Using sprockets-rails 3.2.1
> Using rails 6.0.0.alpha from https://github.com/rails/rails.git (at master@1cc4686)
> Using rubyzip 1.2.2
> Using sass-listen 4.0.0
> Using sass 3.7.2
> Using tilt 2.0.8
> Using sass-rails 5.0.7
> Using selenium-webdriver 3.141.0
> Using spring 2.0.2
> Using spring-watcher-listen 2.0.1
> Using sqlite3 1.3.13
> Using turbolinks-source 5.2.0
> Using turbolinks 5.2.0
> Using web-console 3.7.0 from https://github.com/rails/web-console.git (at master@94c99c9)
> Using webpacker 4.0.0.pre.3 from https://github.com/rails/webpacker.git (at master@bb132d5)
> Bundle complete! 17 Gemfile dependencies, 75 gems now installed.
> Use `bundle info [gemname]` to see where a bundled gem is installed.
>          run  bundle binstubs bundler
> The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
>          run  bundle exec spring binstub --all
> * bin/rake: spring inserted
> * bin/rails: spring inserted
>        rails  webpacker:install
> Traceback (most recent call last):
> 	3: from bin/rails:8:in `<main>'
> 	2: from bin/rails:8:in `require_relative'
> 	1: from /Users/bijan/Desktop/rails6playground/yaberetry/config/boot.rb:4:in `<top (required)>'
> /Users/bijan/Desktop/rails6playground/yaberetry/config/boot.rb:4:in `require': cannot load such file -- bootsnap/setup (LoadError)


Probably this is related to the effect I see that trix is missing.

**Comment by gobijan** [comment]
Generating a project from scratch and then following your guide still doesn't work. Same error.

**Comment by vividmuimui** [comment]
https://github.com/vividmuimui-sandbox/actiontext-sample/commit/446df6c345271b876830a88fe1579f80230aabe3
I resolved same problem with this change.

```rb
# config/initializers/assets.rb

Rails.application.config.assets.paths << Rails.root.join('node_modules')
```

**Comment by fedeagripa** [comment]
> [vividmuimui-sandbox/actiontext-sample@446df6c](https://github.com/vividmuimui-sandbox/actiontext-sample/commit/446df6c345271b876830a88fe1579f80230aabe3)
> I resolved same problem with this change.
> 
> ```ruby
> # config/initializers/assets.rb
> 
> Rails.application.config.assets.paths << Rails.root.join('node_modules')
> ```

Had same issue and worked like a charm, may this not be part of the configuration being done while running `rails action_text:install` ?

**Comment by pepetorres1998** [comment]
> [vividmuimui-sandbox/actiontext-sample@446df6c](https://github.com/vividmuimui-sandbox/actiontext-sample/commit/446df6c345271b876830a88fe1579f80230aabe3)
> I resolved same problem with this change.
> 
> ```ruby
> # config/initializers/assets.rb
> 
> Rails.application.config.assets.paths << Rails.root.join('node_modules')
> ```

I have that line and still giving me the same error.
