### ISSUE TITLE
The Frontend Editor Should be Configurable

### ISSUE THREAD

**Issue by btoconnor** [rails/actiontext#41]
As part of the Rails framework, I think the particular frontend text editor should be configurable.  There's enough plumbing in ActionText to be valuable for every WYSIWYG editor, such as the `action_text_rich_blogs` table for baked content, the ActiveStorage integration and the other conveniences provided by the framework.  The Trix editor is just but one component.

For example, one should be able to selected Quill as their editor of choice in the configuration file:
```ruby
config.action_text.editor = :quill
```
This would then instantiate the Quill editor for any forms built with the `f.rich_text_area` helper.

I've browsed through the source code and have a decent idea of what would need to *change* in order to support something like Quill, but I'm unfamiliar with the best practices with making a configurable framework like this.

I'm happy to take a stab at the code if someone were willing to help guide me along the way with what would need to change to make this happen and get accepted.

Thanks.

**Comment by dhh** [comment]
Please do take a stab! Would love to see the editor be configurable.

**Comment by matthewd** [comment]
>  I'm unfamiliar with the best practices with making a configurable framework like this.

The short answer is to check out existing precedent in other Rails components, like Action Mailer delivery methods, Active Record database adapters, Action Cable transport adapters, and Active Storage backends.

I'd suggest glancing through at least a couple of those, to better get a feel for what's consistent, what's unique to each, and which one seems the best fit to base the new abstraction on.

**Comment by btoconnor** [comment]
Great - thanks for the tips.  I'll see what I can come up with!

**Comment by georgeclaghorn** [comment]
I’m closing this because Action Text has been merged into Rails. If you end up taking a stab at this, please open a PR on [rails/rails](https://github.com/rails/rails). Thanks!
